vich_uploader:
  db_driver: orm

  mappings:
    realisations_image:
      uri_prefix: /images/realisations
      upload_destination: '%kernel.project_dir%/public/images/realisations'
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true  
    experiences_image:
      uri_prefix: /images/experiences
      upload_destination: '%kernel.project_dir%/public/images/experiences'
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true  

    